## Install the CDK

- Install a virtualization provider (hypervisor) for your system such as VirtualBox, VMware, or KVM/libvirt.
- Install Vagrant, from link:https://www.vagrantup.com/[vagrantup.com], or from your operating system’s packages.
- From link:https://access.redhat.com/downloads/content/293/ver=2/rhel---7/2.0.0/x86_64/product-software[Red Hat Customer Portal] download Red Hat Container Tools (cdk-2.0.0.zip) and the RHEL 7.2 Vagrant box that matches your virtualization provider: VirtualBox, VMare, or KVM/libvirt.
- Unzip `cdk-2.0.0.zip` into a directory of your choosing.

Install the required vagrant plugins:

[source]
----
vagrant plugin install vagrant-service-manager
vagrant plugin install vagrant-registration
----

Add the RHEL 7.2 Vagrant box to Vagrant with the command:

[source]
----
vagrant box add --name cdkv2 <path to downloaded .box file>
----

Update CDK Memory and CPU

[source]
----
cd <CDK-PATH>/components/rhel/rhel-ose
export VM_MEMORY=8192
----

Execute Vagrant:

[source]
----
export SUB_USERNAME=<your-subscription-username>
export SUB_PASSWORD=<your-subscription-password>
vagrant up
eval "$(vagrant service-manager env docker)"
----

### Install Openshift Client

You can download and unpack the CLI from the link:https://access.redhat.com/downloads/content/290/ver=3.1/rhel---7/3.1.1.6/x86_64/product-software[Red Hat Customer Portal] for use on Linux, MacOSX, and Windows clients. After logging in with your Red Hat account, you must have an active OpenShift Enterprise subscription to access the downloads page.

link:https://access.redhat.com/downloads/content/290[Download the CLI]

### Access Openshift console

Open Openshift console:  https://10.1.2.2:8443/console/ +
(Accept the certificate and proceed)

Log in Openshift with **openshift-dev/devel** as your credentials in CDK

### Configure the Openshift CLI client

Run:

[source]
----
oc login 10.1.2.2:8443 -u openshift-dev -p devel
# login with **openshift-dev/devel**
----

### Create the project

Now that Openshift should run, create a new project with:

[source]
----
oc new-project reactive-msa
oc policy add-role-to-user view openshift-dev -n reactive-msa
oc policy add-role-to-group view system:serviceaccounts -n reactive-msa
----

The two last instructions give access to the Kubernetes service registry in order to let the different services
discover each other.

If you plan to use the Fabric8 Maven plugin to deploy the microservices, you may need to execute:

[source]
----
export FABRIC8_PROFILES=kubernetes
export KUBERNETES_MASTER=https://10.1.2.2:8443/
----
